# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: install systemd unit file
  template:
    src: home-assistant.service.j2
    dest: "/etc/systemd/system/home-assistant@{{ ha_user }}.service"
    owner: root
    group: root
    mode: 0644

- name: start home-assistant
  systemd:
    name: "home-assistant@{{ ha_user }}"
    daemon_reload: yes
    enabled: yes
    state: started
