# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: restart home-assistant
  service:
    name: "home-assistant@{{ ha_user }}"
    state: restarted
